"""empty message

Revision ID: 070bee55208f
Revises: 
Create Date: 2023-07-06 19:24:48.914740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070bee55208f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('profile_url', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hash_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('writer', 'normal', 'anonymous', 'admin', name='userrole'), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
