"""empty message

Revision ID: 1cb40b1ea11e
Revises: 06805cd42924
Create Date: 2023-07-07 13:54:52.332701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cb40b1ea11e'
down_revision = '06805cd42924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('markdown_content',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('summary',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('markdown_content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###
