"""empty message

Revision ID: ca1d9e75211d
Revises: 1cb40b1ea11e
Create Date: 2023-07-07 14:46:44.242390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca1d9e75211d'
down_revision = '1cb40b1ea11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
